/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    projects: Project;
    articles: Article;
    services: Service;
    faq: Faq;
    steps: Step;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    steps: StepsSelect<false> | StepsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'uk') | ('en' | 'ru' | 'uk')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ru' | 'uk';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alternative text for the media item
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g., "home", "services", "portfolio")
   */
  slug: string;
  /**
   * SEO meta description
   */
  metaDescription?: string | null;
  /**
   * Comma-separated keywords for SEO
   */
  seoKeywords?: string | null;
  /**
   * Image for social sharing (Facebook, LinkedIn, etc.). If not set, the default OG image from Site Settings will be used.
   */
  ogImage?: (number | null) | Media;
  status: 'draft' | 'published';
  blocks?:
    | (
        | {
            variant: 'default' | 'left' | 'right' | 'center';
            headline?: string | null;
            subheadline?: string | null;
            primaryCTA?: {
              text: string;
              url: string;
            };
            secondaryCTA?: {
              text?: string | null;
              url?: string | null;
            };
            backgroundVideo?: (number | null) | Media;
            backgroundImage?: (number | null) | Media;
            titleBrand?: string | null;
            title?: string | null;
            subtitle?: string | null;
            paragraph?: string | null;
            buttonText?: string | null;
            buttonLink?: string | null;
            variantBackgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Unique identifier for this section (e.g., "mission", "approach", "partnership")
             */
            sectionIdentifier: string;
            title: string;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            content_html?: string | null;
            /**
             * Show this section on the website
             */
            isVisible?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            media: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            advantages?:
              | {
                  /**
                   * Emoji icon (e.g., "⚡", "🎨", "🔍")
                   */
                  icon: string;
                  title: string;
                  description?: string | null;
                  points?:
                    | {
                        point: string;
                        id?: string | null;
                      }[]
                    | null;
                  order?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'advantages';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Select services to display
             */
            services?: (number | Service)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesBlock';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Select projects to display
             */
            projects?: (number | Project)[] | null;
            showAllButton?: boolean | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolio';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Select steps to display
             */
            steps?: (number | Step)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsBlock';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            /**
             * Select FAQ items to display
             */
            faqs?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            stats?:
              | {
                  number: number;
                  label: string;
                  /**
                   * Optional icon (emoji or iconify name)
                   */
                  icon?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            showNameField?: boolean | null;
            showEmailField?: boolean | null;
            showPhoneField?: boolean | null;
            showMessageField?: boolean | null;
            buttonText?: string | null;
            policyText?: string | null;
            policyLink?: string | null;
            successMessage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  description?: string | null;
  /**
   * URL-friendly identifier (e.g., "corporate-websites")
   */
  slug: string;
  list?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Service price (e.g., "800 $")
   */
  price?: string | null;
  /**
   * Discounted price (e.g., "599 $")
   */
  price_discount?: string | null;
  /**
   * Iconify icon name (e.g., "twemoji:briefcase")
   */
  icon?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  subtitle?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  advantages?: string | null;
  /**
   * URL-friendly identifier (e.g., "dobro-med-odesa")
   */
  slug: string;
  /**
   * Link to the live project website
   */
  url?: string | null;
  image: number | Media;
  /**
   * Show this project on the homepage
   */
  featured?: boolean | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steps".
 */
export interface Step {
  id: number;
  /**
   * Step number (e.g., "01", "02", "03")
   */
  step: string;
  /**
   * Emoji icon (e.g., "📞", "🎯", "📝")
   */
  icon: string;
  title: string;
  description?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category?: ('general' | 'services' | 'portfolio' | 'pricing' | 'other') | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title if not provided)
   */
  slug: string;
  /**
   * Short summary for article preview
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  publishedDate?: string | null;
  /**
   * Article author name
   */
  author?: string | null;
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email?: string | null;
  phone: string;
  message?: string | null;
  status: 'new' | 'contacted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'steps';
        value: number | Step;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  metaDescription?: T;
  seoKeywords?: T;
  ogImage?: T;
  status?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              variant?: T;
              headline?: T;
              subheadline?: T;
              primaryCTA?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              backgroundVideo?: T;
              backgroundImage?: T;
              titleBrand?: T;
              title?: T;
              subtitle?: T;
              paragraph?: T;
              buttonText?: T;
              buttonLink?: T;
              variantBackgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              sectionIdentifier?: T;
              title?: T;
              content?: T;
              content_html?: T;
              isVisible?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              id?: T;
              blockName?: T;
            };
        advantages?:
          | T
          | {
              title?: T;
              subtitle?: T;
              advantages?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    points?:
                      | T
                      | {
                          point?: T;
                          id?: T;
                        };
                    order?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              services?: T;
              id?: T;
              blockName?: T;
            };
        portfolio?:
          | T
          | {
              title?: T;
              subtitle?: T;
              projects?: T;
              showAllButton?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
        stepsBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              steps?: T;
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              title?: T;
              subtitle?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              title?: T;
              subtitle?: T;
              stats?:
                | T
                | {
                    number?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              subtitle?: T;
              showNameField?: T;
              showEmailField?: T;
              showPhoneField?: T;
              showMessageField?: T;
              buttonText?: T;
              policyText?: T;
              policyLink?: T;
              successMessage?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  description?: T;
  advantages?: T;
  slug?: T;
  url?: T;
  image?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  publishedDate?: T;
  author?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  list?:
    | T
    | {
        item?: T;
        id?: T;
      };
  price?: T;
  price_discount?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "steps_select".
 */
export interface StepsSelect<T extends boolean = true> {
  step?: T;
  icon?: T;
  title?: T;
  description?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site settings including header, footer, contact information, and social media
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Main site logo
   */
  logo?: (number | null) | Media;
  navigation?:
    | {
        label: string;
        /**
         * URL or anchor link (e.g., "/services" or "#contact")
         */
        url: string;
        visibility?: ('all' | 'desktop' | 'mobile') | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    text?: string | null;
    url?: string | null;
  };
  /**
   * Logo displayed in footer (can be different from header logo)
   */
  footerLogo?: (number | null) | Media;
  /**
   * Company description or information displayed in footer
   */
  companyInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Organize footer links into groups (e.g., Services, Company)
   */
  footerLinkGroups?:
    | {
        title: string;
        links: {
          label: string;
          url: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  email: string;
  phone?: string | null;
  /**
   * Company physical address
   */
  address?: string | null;
  workingHours?: {
    weekdays?: string | null;
    weekend?: string | null;
  };
  socialLinks?:
    | {
        platform: 'telegram' | 'whatsapp' | 'viber' | 'instagram' | 'facebook' | 'linkedin' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  heroTitle1?: string | null;
  heroTitle2?: string | null;
  heroText?: string | null;
  consultButtonText?: string | null;
  aboutTitle?: string | null;
  aboutSubtitle?: string | null;
  aboutParagraph?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  advTitle?: string | null;
  advantages?:
    | {
        /**
         * Emoji icon (e.g., "⚡", "🎨", "🔍")
         */
        icon: string;
        title: string;
        description?: string | null;
        points?:
          | {
              point: string;
              id?: string | null;
            }[]
          | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  statsClients?: number | null;
  statsYears?: number | null;
  statsProjects?: number | null;
  bannerTitle?: string | null;
  bannerText1?: string | null;
  bannerText2?: string | null;
  bannerButtonText?: string | null;
  bannerSubtext?: string | null;
  bannerActive?: boolean | null;
  /**
   * Base URL of the site, e.g. "https://veb-dev.com" (without trailing slash). Used for sitemap, canonical URLs, and social sharing.
   */
  siteUrl?: string | null;
  /**
   * When disabled, robots.txt and meta robots will disallow indexing (recommended while the site is under construction).
   */
  allowIndexing?: boolean | null;
  /**
   * Fallback <title> for pages that do not provide their own.
   */
  defaultMetaTitle?: string | null;
  /**
   * Fallback description for pages that do not provide their own.
   */
  defaultMetaDescription?: string | null;
  /**
   * Used for social sharing (Facebook, LinkedIn, etc.) when a page does not set its own og:image.
   */
  defaultOgImage?: (number | null) | Media;
  analytics?: {
    /**
     * Full HTML/JS snippet that will be injected into the <head>. You can paste complete <script>...</script> blocks (e.g. Google Analytics, GTM, pixels) or other tags (meta, link, etc.).
     */
    headScript?: string | null;
    /**
     * Full HTML/JS snippet that will be injected right before </body>. You can paste complete <script>...</script> blocks (e.g. chat widgets, heatmaps) or other HTML.
     */
    bodyEndScript?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        visibility?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  footerLogo?: T;
  companyInfo?: T;
  footerLinkGroups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  email?: T;
  phone?: T;
  address?: T;
  workingHours?:
    | T
    | {
        weekdays?: T;
        weekend?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  heroTitle1?: T;
  heroTitle2?: T;
  heroText?: T;
  consultButtonText?: T;
  aboutTitle?: T;
  aboutSubtitle?: T;
  aboutParagraph?: T;
  advTitle?: T;
  advantages?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        points?:
          | T
          | {
              point?: T;
              id?: T;
            };
        order?: T;
        id?: T;
      };
  statsClients?: T;
  statsYears?: T;
  statsProjects?: T;
  bannerTitle?: T;
  bannerText1?: T;
  bannerText2?: T;
  bannerButtonText?: T;
  bannerSubtext?: T;
  bannerActive?: T;
  siteUrl?: T;
  allowIndexing?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  analytics?:
    | T
    | {
        headScript?: T;
        bodyEndScript?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}